"use client";

import './styles/globals.scss'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { useEffect } from "react";

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
